### ISSUE TITLE
xml2net example not working

### ISSUE THREAD

**Issue by ghost** [KeithSloan/xml2net#2]
Receiving these errors when trying to convert Transistor.fzz using xml2net:

```
Processing File : Transistor.fzz
Output File : Transistor.net
Traceback (most recent call last):
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xml2net.py", line 87, in <module>
    parser.parse(XMLfile)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.8/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python3.8/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: Transistor.fzz:1:2: not well-formed (invalid token)
```

**Comment by KeithSloan** [comment]
Changes to KiCAD means that KiCAD is no longer able to import the net files see issue #1

Also it works or more accurately used to work on an export xml file, so don't understand why you are trying to use a .fzz file.

**Comment by ghost** [comment]
@KeithSloan I apologize, I didn't see this step: "Export circuit to XML Netlist - File | Export Netlist" in the readme.

**Comment by KeithSloan** [comment]
No problem - I will close this issue.
